# Generated by Django 5.2.4 on 2025-11-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtítulo (Opcional)')),
                ('button_text', models.CharField(max_length=50, verbose_name='Texto do Botão')),
                ('button_link', models.CharField(max_length=255, verbose_name='Link do Botão (ex: /produtos)')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Imagem de Fundo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
