# Generated by Django 6.0.1 on 2026-01-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['-is_active'], 'verbose_name': 'Banner inicial', 'verbose_name_plural': 'Banners iniciais'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
