# Generated by Django 5.2.4 on 2025-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='Centro', max_length=100),
        ),
    ]
