# Generated by Django 5.2.4 on 2025-11-16 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de Desconto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(verbose_name='Válido até')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para uso ilimitado', null=True, verbose_name='Limite de Uso')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Vezes Usado')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mínimo de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('returned', 'Devolvido')], default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order')),
            ],
        ),
    ]
