# Generated by Django 5.2.4 on 2025-11-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
        migrations.AddField(
            model_name='shipping',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensagem de erro caso a geração de etiqueta falhe', null=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='label_generated_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora que a etiqueta foi gerada', null=True, verbose_name='Etiqueta Gerada em'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='label_url',
            field=models.URLField(blank=True, help_text='URL do PDF da etiqueta gerada', max_length=500, null=True, verbose_name='URL da Etiqueta'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='melhor_envio_order_id',
            field=models.CharField(blank=True, help_text='ID do pedido gerado na API do Melhor Envio', max_length=100, null=True, verbose_name='ID Pedido Melhor Envio'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de geração de etiqueta', verbose_name='Tentativas de Retry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_process', 'Em Processo'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('returned', 'Devolvido'), ('failed', 'Falhou')], default='pending', max_length=50),
        ),
    ]
