# Generated by Django 5.2.4 on 2025-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_payment_options_alter_shipping_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='preference_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
