# Generated by Django 5.2.4 on 2025-12-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_transaction_id_payment_preference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_document',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
