# Generated by Django 6.0.1 on 2026-01-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_payment_payer_document'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at', 'discount_percentage'], 'verbose_name': 'Cupom de Desconto', 'verbose_name_plural': 'Cupons de Desconto'},
        ),
        migrations.AddField(
            model_name='shipping',
            name='service_id',
            field=models.IntegerField(blank=True, help_text='ID numérico do serviço escolhido (ex: 1=PAC, 2=SEDEX)', null=True, verbose_name='ID do Serviço (Melhor Envio)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=50, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Pagamento (MP*)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_document',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Documento do Pagador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='preference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Preferência'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_process', 'Em Processo'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Custo de Envio'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega Estimada'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('returned', 'Devolvido'), ('failed', 'Falhou')], default='pending', max_length=50, verbose_name='Status do Envio'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Rastreamento'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
