# Generated by Django 6.0.1 on 2026-01-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitem_options_and_more'),
        ('products', '0008_essence_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='essence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.essence', verbose_name='Essência'),
        ),
    ]
