# Generated by Django 6.0.1 on 2026-01-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_essence'),
        ('products', '0010_productcustomization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor/Texto')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='cart.cartitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcustomization', verbose_name='Opção Escolhida')),
            ],
        ),
    ]
