# Generated by Django 6.0.1 on 2026-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalhes da Personalização'),
        ),
    ]
