# Generated by Django 6.0.1 on 2026-01-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price', 'stock_quantity', 'category', 'size', 'is_bestseller', 'created_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='essence',
        ),
        migrations.AddField(
            model_name='size',
            name='milliliters',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso ml'),
        ),
    ]
