# Generated by Django 5.2.4 on 2025-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essence',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Essência', 'verbose_name_plural': 'Essências'},
        ),
        migrations.AddField(
            model_name='essence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='essences/', verbose_name='Imagem da Essência'),
        ),
        migrations.AddField(
            model_name='essence',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está Ativa?'),
        ),
        migrations.AddField(
            model_name='essence',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
    ]
