# Generated by Django 5.2.4 on 2025-10-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_essence_options_essence_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essence',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
