# Generated by Django 6.0.1 on 2026-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_remove_product_essence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='milliliters',
        ),
        migrations.AddField(
            model_name='size',
            name='unit',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='size',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso'),
        ),
    ]
