# Generated by Django 6.0.1 on 2026-01-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_size_milliliters_size_unit_alter_size_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gramas'), ('ml', 'mililitros')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
