# Generated by Django 6.0.1 on 2026-01-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='unit',
            field=models.CharField(choices=[('g', 'gramas'), ('ml', 'mililitros')], default='g', max_length=2, verbose_name='Unidade de Medida'),
        ),
    ]
