# Generated by Django 5.2.4 on 2025-10-16 00:20

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """
    Gera slugs automaticamente para todas as essências que não têm slug.
    """
    Essence = apps.get_model('products', 'Essence')

    for essence in Essence.objects.all():
        if not essence.slug:
            base_slug = slugify(essence.name)
            slug = base_slug
            counter = 1

            # Verificar se o slug já existe e adicionar número se necessário
            while Essence.objects.filter(slug=slug).exclude(pk=essence.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            essence.slug = slug
            essence.save()
            print(f"Slug gerado para '{essence.name}': {slug}")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
    ]
