# Generated by Django 5.2.4 on 2025-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_description_product_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='É um mais vendido?'),
        ),
    ]
