# Generated by Django 6.0.1 on 2026-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_size_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='essence',
            name='categorias',
            field=models.ManyToManyField(related_name='essences', to='products.category', verbose_name='Categorias'),
        ),
    ]
