# Generated by Django 6.0.1 on 2026-01-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_image_alter_essence_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Opção')),
                ('instruction', models.CharField(blank=True, max_length=255, verbose_name='Instrução para o cliente')),
                ('input_type', models.CharField(choices=[('text', 'Texto Livre (Cliente digita)'), ('select', 'Seleção (Cliente escolhe de uma lista)'), ('boolean', 'Sim/Não')], default='text', max_length=20, verbose_name='Tipo de Entrada')),
                ('available_options', models.TextField(blank=True, null=True, verbose_name='Opções disponíveis (se houver)')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Custo Adicional (Unitário)')),
                ('free_above_quantity', models.PositiveIntegerField(blank=True, help_text='Se o cliente comprar acima dessa quantidade, essa personalização sai de graça.', null=True, verbose_name='Grátis a partir de X unidades')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='products.product', verbose_name='Produto')),
            ],
        ),
    ]
