# Generated by Django 6.0.1 on 2026-01-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustomization',
            name='product',
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='products.category', verbose_name='Categoria'),
        ),
    ]
