# Generated by Django 6.0.1 on 2026-01-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productcustomization_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustomization',
            name='required',
        ),
    ]
