# Generated by Django 6.0.1 on 2026-01-17 19:00

import xxlimited_35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productcustomization_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essence',
            old_name='categorias',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='essence',
            name='description',
        ),
        migrations.AddField(
            model_name='essence',
            name='ambient',
            field=models.CharField(default=xxlimited_35.Null, max_length=100, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='essence',
            name='notes',
            field=models.CharField(default=xxlimited_35.Null, max_length=100, verbose_name='Notas Sensoriais'),
        ),
        migrations.AddField(
            model_name='essence',
            name='sensory_profile',
            field=models.CharField(default=xxlimited_35.Null, max_length=100, verbose_name='Perfil Sensorial'),
        ),
    ]
